package com.portfolio.inventory_app.model.enums;

public enum Disponibilidad {
    PRESENTE, VACACIONES, LICENCIA_MATERNIDAD, LICENCIA_PATERNIDAD,
    LICENCIA_ENFERMEDAD, LICENCIA_DUELO, LICENCIA_ESPECIAL,
    LICENCIA_EXAMEN, LICENCIA_MUDANZA, AUSENCIA_JUSTIFICADA, AUSENCIA_INJUSTIFICADA,
    RESERVA_PUESTO;
}
