package com.portfolio.inventory_app.model.enums;

public enum Staff {
    DIRECTOR_EJECUTIVO, DIRECTOR_TECNOLOGIA, DIRECTOR_FINANZAS,
    GERENTE_PRODUCTO, DIRECTOR_OPERACIONES, GERENTE_GENERAL,
    DIRECTOR_COMERCIAL, VENDEDOR, DIRECTOR_MARKETING,
    SECRETARIO, RECEPCIONISTA, AUXILIR_SERVICIO
}
